version: '3'

services:
  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: espace_membre
      MYSQL_USER: devuser
      MYSQL_PASSWORD: 123
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  web:
    build: .
    container_name: php_web
    depends_on:
      - database
    volumes:
      - ./aclab:/var/www/html
      - ./aclab/inscription.php:/var/www/html/index.php
    ports:
      - "8100:80"
    stdin_open: true
    tty: true
